export default {
	'en-US': {
		//头部
		header:{
	  		index: 'Home',
	  		login: 'Login',
	  		exit: 'Exit',
	  		reg: 'Register',
//	  		mobile: 'Mobile',
	  		about: 'About',
	  		language: 'language',
	  		Chinese: 'ZH',
	  		English: 'EN'
	  	},
	  	//左边栏菜单
	  	menu: {
	  		act_man: 'Account',
	  		act_info: 'Information',
	  		act_sec: 'Security',
	  		funds_man: 'Capital',
	  		my_funds: 'My Funds',
	  		coin: 'Mining Coin',
	  		gift: 'Gift Exchange',
	  		voucher: 'Voucher',
	  		order_man: 'Order',
	  		my_order: 'My Supply',
	  		my_shop: 'My Shopping',
	  		cert_man: 'Certificate',
	  		person: 'Personal',
	  		my_resume: 'My Resume',
	  		atten_man: 'Attention',
	  		msg_man: 'Message',
	  		investor: 'Investor Cert',
	  		comp_info: 'Enterprise Info',
	  		flag_shop: 'Flagship Shop',
	  		sub_act: 'Sub-account',
	  	},
	  	//注册、登录、忘记密码等页
		reg: {
			welcome: 'Welcome to login',
			hotline: 'Customer service hotline',
			worktime: 'working hours',
			login: {
	  			viplogin: 'Members Login',
	  			reg: 'Register Now',
	  			remember: 'Remember the username',
	  			forget: 'forget the password',	  			
	  		},
	  		reg: {
	  			have_act: 'I have an account，'
	  		},
	  		mobile: 'mobile',
	  		msgcode: 'msg code',
	  		set_pwd: 'set password',
	  		confirm_pwd: 'confirm',
	  		email: 'email',
	  		captcha: 'captcha'
		},
		user: {
	  		index: {
	  			status: 'User status',
	  			level: 'User level',
	  			comp_cert: 'Certified enterprise',
	  			comp_review: 'Enterprise audit',
	  			off_shelf: 'off-shelf',
	  			review: 'In review',
	  			re_cert: 'Recertification',
	  			leave_comp: 'Leave the company',
	  			shop_view: 'Shop view',
	  			state_funds: 'State funding',
	  			able_balance: 'Available balance',
	  			coin: 'Mining coin',
	  			total: 'Total funds',
	  			recharge: 'recharge',
	  			withdraw: 'withdraw',
	  			detail: 'detail',
	  			new_comp: 'New licensed Users',
	  			purch_info: 'Purchase Information',
	  			pubdate: 'pubdate',
	  			pro_name: 'product name',
	  			quantity: 'quantity',
	  		},
	  		info: {
	  			tit: 'Mining account information',
	  			account: 'Mining account',
	  			status: 'User status',
	  			level: 'User level',
	  			time: 'Registration date',
	  		},
	  		security: {
	  			tip: 'Binding mobile phone number and email can increase the security of user information',
	  			mobile: 'Mobile',
	  			email: 'Bind email',
	  			login_pwd: 'Login password',
	  			funds_pwd: 'Funds password',
	  		},
	  		funds: {
	  			tit: 'Money to preview',
	  			tit_sec: 'Money record',
	  			type: 'type of transaction',
	  			all: 'all',
	  			recharge: 'recharge',
	  			withdraw: 'withdraw',
	  			cut_money: 'cut payment',
	  			trade: 'trade credit',
	  			time_ran: 'time horizon',
	  			seven_days: 'seven days',
	  			one_month: 'one month',
	  			three_month: 'three month',
	  			six_month: 'six month',
	  			time: 'time',
	  			amount: 'amount',
	  			act_type: 'account type',
	  			explain: 'explain',
	  		},
	  		coin: {
	  			tit: 'Money overview',
	  			total_value: 'Total value',
	  			surplus: 'surplus',
	  			used: 'used',
	  			redeem: 'redeem the prize',
	  			coin: 'mining coin',
	  			record: 'for record',
	  		},
	  		gift: {
	  			tit: 'Gift exchange',
	  			value: 'value',
	  			total: 'Total',
	  			used: 'Used',
	  			unused: 'Unused',
	  			gift: 'Gift',
	  			expired: 'Expired',
	  		},
	  		voucher: {
	  			tit: 'Voucher'
	  		},
	  		order: {
				ordinary_goods: 'ordinary goods',
				commodity: 'commodity',
				service_goods: 'service goods',
				order_information: 'order information',
				price: 'price（RMB）',
				order_quantity: 'order quantity',
				order_amount: 'order amount',
				trading_status: 'trading status',
				trading_operations: 'trading operations',
				order_number: 'order number',
				cancel_order: 'cancel order',
				no_data: 'no data',
			},
	  		personal: {
	  			tit: 'Personal data',
	  			tip: 'You have authenticated your personal data and click edit to modify',
	  			edit: 'edit',
	  			majors: 'Majors',
	  			tel: 'Tel',
	  			email: 'Email',
	  			address: 'Address',
	  			self_evaluation: 'Self-evaluation',
	  		},
	  		act_cert: {
	  			tit: 'Personal certificate',
	  			upload: 'upload',
	  			set: 'Setting',
	  			name: 'Name',
	  		},
	  		atten: {
	  			tit: 'Attention type',
	  			all: 'all',
	  			flag_store: 'flagship store',
	  			goods: 'goods',
	  			selling_floor: 'selling floor',
	  			program_trade: 'program trade',
	  			exhibition: 'exhibition',
	  			serving_product: 'serving product',
	  			check_all: 'check all',
	  			unfollow: 'unfollow',
	  			name: 'name',
	  			type: 'type',
	  			time: 'time',
	  			detail: 'detail',
	  			operate: 'operate',
	  			view: 'view',
	  		},
	  		message: {
	  			tit: 'My message',
	  			status: 'status',
	  			title: 'title',
	  			time: 'time',
	  			check_all: 'check all',
	  			delete: 'delete',
	  			unread: 'unread',
	  			read: 'read',
	  			marked_read: 'marked as read'
	  		},
	  	},
	  	comp: {
	  		index: {
	  			company_name: 'Company name',
	  			company_type: 'company type',
	  			main_product: 'main product',
	  			funds_status: 'State funding',
	  			flag_store: 'Flagship store',
	  			todo: 'Todo',
	  			specification: 'specification',
	  			address: 'address',
	  			other: 'other',
	  			take_their: 'take their',
	  			send: 'send',
	  		},
	  		info: {
	  			tit: 'Enterprise information',
	  			tip: 'Warm Tips: Please upgrade to "Gold Certified Enterprise" for more value-added services.',
	  			name: 'Company name',
	  			state: '',
	  			funds_pwd: 'Funds password',
	  			create_time: 'Established time',
	  			tip2: 'Set or modify the funds password',
	  		},
	  		funds: {
	  			status: 'status',
	  			all: 'all',
	  			expenditure: 'expenditure',
	  			income: 'income',
	  			freeze: 'freeze',
	  		},
	  		coin: {
	  			
	  		},
	  		gift: {
	  			
	  		},
	  		voucher: {
	  			
	  		},
	  		investor_data: {
	  			tit: 'Investor information',
	  			tip: 'You have certified investor information, clicking “Edit” to modify.',
	  			amount: 'Investment amount',
	  			currency: 'currency',
	  			mode: 'Way of investment',
	  			minerals: 'Minerals',
	  			address: 'Project location',
	  			require: 'Requirement of project',  			
	  		},
	  		comp_data: {
	  			tit: 'Enterprise information',
	  			tip: 'You have verified the enterprise information and click edit to modify',
	  			edit: '编辑',
	  			tip2: 'Your information is being certified!',
	  			comp_name: 'Company Name',
	  			address: 'company address',
	  			post: 'Postcode',
	  			reg_time: 'Registration time',
	  			reg_capital: 'Registered capital',
	  			main_pro: 'Main products',
	  			website: 'website',
	  			social_code: 'Social credit code',
	  			bues_types: 'Business types',
	  			bues_range: 'Business Scope',
	  			comp_type: 'Enterprise type',
	  			introduction: 'Company Profile',
	  			tit2: 'Qualification information',
	  			tit3: 'Business information',
	  			staff: 'Employee Number',
	  			turnover: 'Turnover',
	  			plant: 'Plant Area',
	  			export: 'Annual Exports',
	  			quality: 'Quality Control',
	  			process: 'External Customized Processing',
	  			cert_system: 'Certification Management System',
	  			tit4: 'Contact information',  			
	  			contact: 'Contacter',
	  			tel: 'Telephone',
	  			email: 'Email',
	  			department: 'Department',
	  			position: 'Position',
	  			tit5: 'Invoice information',  
	  			bill_adress: 'Billing Address',
	  			bill_type: 'Billing type',
	  			taxpayer_id: '纳税人识别号',
	  			bank: 'deposit bank',
	  			mobile: 'Billing call',
	  		},
	  		comp_cert: {
	  			tit: '',
	  		},
	  		sub_act: {
	  			tit: 'Sub-account management',
	  			all: 'all',
	  			admin: 'Admin',
	  			bureaucrat: 'bureaucrat',
	  			business_operator: 'business operator',
	  			financial_operator: 'financial operator',
	  			staff: 'staff',
	  			account: 'account',
	  			position: 'position',
	  			tel: 'tel',
	  			email: 'email',
	  			status: 'status',
	  			operate: 'operate',
	  			remark: 'remark',
	  			normal: 'normal',
	  			applying: 'applying',
	  			level: 'leave',
	  		},			
	  	},
		//placeholder
		placeholder: {
			act_placeh: 'mining account/mobile/email',
			pwd: 'password',
			mobile: 'Please enter your phone number!',
			msgcode: 'Please enter the text message verification code!',
			setpwd: 'Please set the login password!',
			confirmpwd: 'Please confirm the login password!',
			email: 'Please enter your mailbox!'
		},
		comm: {
			more: 'more',
			user: 'Personal',
			comp: 'Enterprise',
			user_cert: 'Personal center',
			comp_cert: 'Enterprise Center',
			no_data: 'no data！',
			get_code: 'get code',
			submit: 'Submit'
		},
		name: 'my name is zhoujingang'
	}
}