export default {
	'zh-CN': {
		//头部
		header: {
			index: '首页',
			login: '登录',
			exit: '退出',
			reg: '注册',
//			mobile: '手机版',
			about: '关于我们',
			language: '语言',
			Chinese: '中文',
			English: '英文'
		},
		//左边栏菜单
		menu: {
			act_man: '账户管理',
			act_info: '账户信息',
			act_sec: '账户安全',
			funds_man: '资金管理',
			my_funds: '我的资金',
			coin: '矿业币',
			gift: '礼品兑换',
			voucher: '代金券',
			order_man: '订单管理',
			my_order: '我的供应',
			my_shop: '我的采购',
			cert_man: '认证中心',
			person: '个人认证',
			my_resume: '我的简历',
			atten_man: '关注中心',
			msg_man: '消息中心',
			investor: '投资人认证',
			comp_info: '企业信息',
			flag_shop: '旗舰店管理',
			sub_act: '子账户管理',
		},
		//注册、登录、忘记密码等页
	  	reg: {
	  		welcome: '欢迎登录',
	  		hotline: '热线电话',
	  		worktime: '工作时间',
	  		login: {
	  			viplogin: '会员登录',
	  			reg: '立即注册',
	  			remember: '记住用户名',
	  			forget: '忘记密码',
	  		},
	  		reg: {
	  			have_act: '我已有账户，'
	  		},
	  		mobile: '手机号',
	  		msgcode: '短信验证码',
	  		set_pwd: '设置登录密码',
	  		confirm_pwd: '确认密码',
	  		email: '邮箱',
	  		captcha: '验证码'
	  	},
	  	user: {
	  		index: {
	  			status: '用户身份',
	  			level: '用户等级',
	  			comp_cert: '您已认证企业',
	  			comp_review: '企业审核中',
	  			off_shelf: '已经下架',
	  			review: '审核中',
	  			re_cert: '重新认证',
	  			leave_comp: '离开公司',
	  			shop_view: '查看公司店铺',
	  			state_funds: '资金状态',
	  			able_balance: '可用余额',
	  			coin: '矿业币',
	  			total: '资金总额',
	  			recharge: '充值',
	  			withdraw: '提现',
	  			detail: '明细',
	  			new_comp: '新入驻的企业',
	  			purch_info: '求购资源信息',
	  			pubdate: '发布时间',
	  			pro_name: '商品名称',
	  			quantity: '订购数量',
	  		},
	  		info: {
	  			tit: '矿业账号信息',
	  			account: '矿业账号',
	  			status: '用户身份',
	  			level: '用户等级',
	  			time: '注册时间',
	  		},
	  		security: {
	  			tip: '绑定手机号和邮箱可增加您的用户信息安全等级。',
	  			mobile: '手机号码',
	  			email: '绑定邮箱',
	  			login_pwd: '登录密码',
	  			funds_pwd: '资金密码',
	  		},
	  		funds: {
	  			tit: '资金预览',
	  			tit_sec: '资金记录',
	  			type: '交易类型',
	  			all: '全部',
	  			recharge: '充值',
	  			withdraw: '提现',
	  			cut_money: '扣款',
	  			trade: '交易扣款',
	  			time_ran: '时间范围',
	  			seven_days: '最近七天',
	  			one_month: '1个月',
	  			three_month: '3个月',
	  			six_month: '6个月',
	  			time: '时间',
	  			amount: '金额(元)',
	  			act_type: '账户类型',
	  			explain: '说明',
	  		},
	  		coin: {
	  			tit: '资金总览',
	  			total_value: '总矿业币价值（元）',
	  			surplus: '剩余矿业币',
	  			used: '已使用',
	  			redeem: '兑换奖品',
	  			coin: '矿业币',
	  			record: '兑换记录',
	  		},
	  		gift: {
	  			tit: '礼品兑换',
					value: '价值',
	  			total: '总礼品',
	  			used: '已使用',
	  			unused: '未使用',
	  			gift: '礼品',
	  			expired: '已过期',
	  		},
	  		voucher: {
	  			tit: '代金券',
	  		},
	  		order: {
					ordinary_goods: '普通商品',
					commodity: '大宗商品',
					service_goods: '服务商品',
					order_information: '订单信息',
					price: '单价（元）',
					order_quantity: '订购数量',
					order_amount: '订购金额',
					trading_status: '交易状态',
					trading_operations: '交易操作',
					order_number: '订单号',
					cancel_order: '取消订单',
					no_data: '暂无数据',
				},
	  		personal: {
	  			tit: '个人资料',
	  			tip: '您已认证个人资料，点击编辑可进行修改',
	  			edit: '编辑',
	  			majors: '专业',
	  			tel: '联系电话',
	  			email: '邮箱',
	  			address: '地址',
	  			self_evaluation: '自我评价',
	  		},
	  		act_cert: {
	  			tit: '个人认证',	
	  			upload: '上传图片',
	  			set: '个人账号的资料设置',
	  			name: '真实姓名',
	  		},
	  		atten: {
	  			tit: '关注类型',
	  			all: '全部',
	  			flag_store: '旗舰店',
	  			goods: '商品',
	  			selling_floor: '交易厅',
	  			program_trade: '项目交易',
	  			exhibition: '会展',
	  			serving_product: '服务产品',
	  			check_all: '全选',
	  			unfollow: '取消关注',
	  			name: '名称',
	  			type: '类型',
	  			time: '时间',
	  			detail: '详情',
	  			operate: '操作',
	  			view: '查看',
	  		},
	  		message: {
	  			tit: '我的信件',
	  			status: '状态',
	  			title: '标题',
	  			time: '时间',
	  			check_all: '全选',
	  			delete: '删除',
	  			unread: '未读',
	  			read: '已读',
	  			marked_read: '标为已读',
	  		},
	  	},
	  	comp: {
	  		index: {
	  			company_name: '企业名称',
	  			company_type: '企业类型',
	  			main_product: '主营产品',
	  			funds_status: '资金状态',
	  			flag_store: '企业旗舰店',
	  			todo: '待办事项提醒',
	  			specification: '规格',
	  			address: '收货地址',
	  			other: '其它',
	  			take_their: '自提',
	  			send: '送到',
	  		},
	  		info: {
	  			tit: '企业信息',
	  			tip: '温馨提示: 升级为“金牌认证企业”，您可获得更多超值服务。',
	  			name: '企业名称',
	  			state: '企业身份',
	  			funds_pwd: '资金密码',
	  			create_time: '成立时间',
	  			tip2: '设置或修改资金密码',
	  		},
	  		funds: {
	  			status: '状态',
	  			all: '全部',
	  			expenditure: '支出',
	  			income: '收入',
	  			freeze: '冻结',
	  		},
	  		coin: {
		  			
	  		},
	  		gift: {
	  			
	  		},
	  		voucher: {
	  			
	  		},
	  		investor_data: {
	  			tit: '投资人信息',
	  			tip: '您已认证投资人资料，点击编辑可进行修改',
	  			amount: '可投金额',
	  			currency: '币种',
	  			mode: '投资方式',
	  			minerals: '矿种分类',
	  			address: '项目所在地',
	  			require: '项目要求'
	  		},
	  		comp_data: {
	  			tit: '企业信息',
	  			tip: '您已认证企业资料，点击编辑可进行修改',
	  			edit: '编辑',
	  			tip2: '您的资料正在认证中!',
	  			comp_name: '企业名称',
	  			address: '企业地址',
	  			post: '邮政编码',
	  			reg_time: '注册时间',
	  			reg_capital: '注册资本',
	  			main_pro: '主营产品',
	  			website: '网站',
	  			social_code: '统一社会信用代码',
	  			bues_types: '经营种类',
	  			bues_range: '经营范围',
	  			comp_type: '企业类型',
	  			introduction: '企业简介',
	  			tit2: '资质信息',
	  			tit3: '经营信息',
	  			staff: '员工人数',
	  			turnover: '营业额',
	  			plant: '厂房面积',
	  			export: '年出口额',
	  			quality: '质量控制',
	  			process: '是否对外加工定制',
	  			cert_system: '认证管理体系',
	  			tit4: '联系信息',  			
	  			contact: '联系人姓名',
	  			tel: '联系电话',
	  			email: '联系邮箱',
	  			department: '所属部门',
	  			position: '职位',
	  			tit5: '发票信息',  
	  			bill_adress: '开票地址',
	  			bill_type: '开票类型',
	  			taxpayer_id: '纳税人识别号',
	  			bank: '开户银行',
	  			mobile: '开票电话',
	  		},
	  		comp_cert:{
	  			tit: '',
	  		},
	  		sub_act: {
	  			tit: '子账号管理',
	  			all: '全部',
	  			admin: '管理员',
	  			bureaucrat: '行政管理员',
	  			business_operator: '业务操作员',
	  			financial_operator: '财务操作员',
	  			staff: '员工',
	  			account: '账号',
	  			position: '职位',
	  			tel: '手机',
	  			email: '邮箱',
	  			status: '状态',
	  			operate: '操作',
	  			remark: '备注',
	  			normal: '正常',
	  			applying: '申请中',
	  			level: '离开',
	  		}
	  	},
  		//placeholder
  		placeholder: {
			act_placeh: '矿业账号/手机号/邮箱',
			pwd: '密码',
			mobile: '请输入手机号！',
			msgcode: '请输入短信验证码！',
			setpwd: '请设置登录密码！',
			confirmpwd: '请确认登录密码！',
			email: '请输入邮箱！'
		},
		comm: {
			more: '更多',
			user: '个人中心',
			comp: '企业中心',
			user_cert: '个人中心',
			comp_cert: '企业中心',
			no_data: '暂无数据!',
			get_code: '获取验证码',
			submit: '提交'
		},
		name: '周锦钢'
	}
}